import React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

export const PricingSection = () => (
  <section id="precios" className="py-24 px-6">
    <div className="max-w-6xl mx-auto text-center mb-16">
      <h2 className="text-5xl font-bold text-gray-900 mb-6">Planes y Precios</h2>
      <div className="w-24 h-1 bg-gradient-to-r from-blue-600 to-indigo-600 mx-auto rounded-full" />
    </div>
    <div className="grid lg:grid-cols-2 gap-8 max-w-4xl mx-auto">      <Card className="group bg-white/60 backdrop-blur-2xl shadow-xl rounded-3xl overflow-hidden hover:shadow-2xl transition-all duration-500">        <div className="absolute inset-0 bg-gradient-to-br from-blue-600/5 to-indigo-600/5 opacity-0 group-hover:opacity-100 transition-opacity duration-500" />        <CardHeader className="relative z-10 text-center pb-6">          <CardTitle className="text-3xl font-light text-gray-900 mb-2">Plan Mensual</CardTitle>          <CardDescription className="text-gray-600 mb-6">Ideal para uso frecuente</CardDescription>          <div className="text-5xl font-light text-blue-600 mb-2">$15.000 <span className="text-xl text-gray-400 font-normal">/mes</span></div>        </CardHeader>        <CardContent className="relative z-10">          <ul className="space-y-4 mb-8">            {['Estacionamiento ilimitado','8 lavados incluidos','Acceso prioritario','Carga gratuita','App premium'].map(item=> (<li key={item} className="flex items-center text-gray-700"><span className="w-2 h-2 bg-blue-600 rounded-full mr-3" />{item}</li>))}          </ul>          <Button className="w-full bg-blue-600 text-white py-4 rounded-2xl hover:scale-105 transition-all duration-300">Suscribirse</Button>        </CardContent>      </Card>      <Card className="group bg-white/60 backdrop-blur-2xl shadow-xl rounded-3xl overflow-hidden hover:shadow-2xl transition-all duration-500">        <div className="absolute inset-0 bg-gradient-to-br from-green-600/5 to-emerald-600/5 opacity-0 group-hover:opacity-100 transition-opacity duration-500" />        <CardHeader className="relative z-10 text-center pb-6">          <CardTitle className="text-3xl font-light text-gray-900 mb-2">Pago por Uso</CardTitle>          <CardDescription className="text-gray-600 mb-6">Flexibilidad total</CardDescription>          <div className="text-5xl font-light text-green-600 mb-2">Variable</div>        </CardHeader>        <CardContent className="relative z-10">          <ul className="space-y-4 mb-8">            {['Estacionamiento: $200/hora','Lavado completo: $2.500','Carga eléctrica: $150/kWh','Descuento combo: 15%','Sin compromisos'].map(item=> (<li key={item} className="flex items-center text-gray-700"><span className="w-2 h-2 bg-green-600 rounded-full mr-3" />{item}</li>))}          </ul>          <Button variant="outline" className="w-full border-2 border-green-600 text-green-600 py-4 rounded-2xl hover:scale-105 transition-all duration-300">Usar Ahora</Button>        </CardContent>      </Card>    </div>  </section>
);
